import { listProjects, saveProject, removeProject, connectFolder, exportProject, exportManuscript } from './storage.js';
import { makeProject, uid, wordCount, totalWords } from './projects.js';
import { askAI } from './ai.js';

const $ = selector => document.querySelector(selector); const $$ = selector => [...document.querySelectorAll(selector)];
let projects = [], project, chapter, saveTimer, aiPending;
const escape = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const toast = message => { $('#toast').textContent = message; $('#toast').classList.add('show'); setTimeout(() => $('#toast').classList.remove('show'), 2600); };
const formatDate = value => new Intl.DateTimeFormat('de', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

async function requireAuth() {
  try {
    if ((await fetch('/api/session')).ok) return true;
  } catch { /* Redirect to the sign-in page below. */ }
  location.replace('index.html');
  return false;
}
async function start() { if (!(await requireAuth())) return; projects = await listProjects(); renderDashboard(); }
function renderDashboard(showTrash = false) {
  $('#dashboard').classList.remove('hidden'); $('#workspace').classList.add('hidden'); $('#export-btn').classList.add('hidden'); $('#crumb').textContent = '';
  const visible = projects.filter(item => Boolean(item.trashedAt) === showTrash); $('#trash-count').textContent = projects.filter(item => item.trashedAt).length;
  $('#empty').classList.toggle('hidden', visible.length > 0 || showTrash);
  $('#projects').innerHTML = visible.map(item => `<article class="project-card"><div class="cover"></div><small>${escape(item.genre || 'BUCHPROJEKT')}</small><h3>${escape(item.title)}</h3><p>${escape(item.description || 'Deine Geschichte wartet darauf, weitererzählt zu werden.')}</p><div class="project-meta"><span>${totalWords(item).toLocaleString('de')} Wörter</span><span>${item.chapters.length} Kapitel</span></div><footer><small>${formatDate(item.updatedAt)}</small>${showTrash ? `<span><button data-restore="${item.id}">Wiederherstellen</button><button class="danger" data-purge="${item.id}">Endgültig löschen</button></span>` : `<span><button class="danger" data-trash="${item.id}">Löschen</button><button class="primary" data-open="${item.id}">Öffnen →</button></span>`}</footer></article>`).join('');
  $$('[data-open]').forEach(b => b.onclick = () => openProject(b.dataset.open));
  $$('[data-trash]').forEach(b => b.onclick = () => trashProject(b.dataset.trash));
  $$('[data-restore]').forEach(b => b.onclick = async () => { const p = projects.find(x => x.id === b.dataset.restore); p.trashedAt = null; await saveProject(p); renderDashboard(true); });
  $$('[data-purge]').forEach(b => b.onclick = () => purgeProject(b.dataset.purge));
}
function openProject(id) { project = projects.find(item => item.id === id); chapter = project.chapters[0]; $('#dashboard').classList.add('hidden'); $('#workspace').classList.remove('hidden'); $('#export-btn').classList.remove('hidden'); $('#book-title').textContent = project.title; $('#crumb').textContent = `/ ${project.title}`; renderChapters(); selectChapter(chapter?.id); showView('write'); updateStorageState(); }
function renderChapters() { $('#chapter-list').innerHTML = project.chapters.map((item, i) => `<div class="chapter ${item.id === chapter?.id ? 'active' : ''}"><button data-chapter="${item.id}">${i + 1}. ${escape(item.title)}</button><button class="menu" data-chapter-menu="${item.id}">•••</button></div>`).join(''); $$('[data-chapter]').forEach(b => b.onclick = () => selectChapter(b.dataset.chapter)); $$('[data-chapter-menu]').forEach(b => b.onclick = () => chapterMenu(b.dataset.chapter)); }
function selectChapter(id) { chapter = project.chapters.find(item => item.id === id); if (!chapter) return; $('#chapter-title').value = chapter.title; $('#editor').value = chapter.content; renderChapters(); updateCount(); }
function updateCount() { $('#word-count').textContent = `${wordCount($('#editor').value).toLocaleString('de')} Wörter · ${$('#editor').value.length.toLocaleString('de')} Zeichen`; }
function queueSave() { $('#save-state').textContent = 'Speichert …'; clearTimeout(saveTimer); saveTimer = setTimeout(async () => { try { await saveProject(project); $('#save-state').textContent = 'Gespeichert ✓'; } catch (error) { $('#save-state').textContent = 'Speichern fehlgeschlagen'; toast(error.message); } }, 750); }
function showView(name) { $$('#sections button').forEach(b => b.classList.toggle('active', b.dataset.view === name)); $$('.view').forEach(v => v.classList.add('hidden')); $(`#${name}-view`).classList.remove('hidden'); if (name !== 'write') renderDataView(name); }
function viewHeader(title, description, button) { return `<div class="view-toolbar"><div><p class="eyebrow">STORY BIBLE</p><h1>${title}</h1><p class="view-sub">${description}</p></div>${button ? `<button class="primary" id="view-add">＋ ${button}</button>` : ''}</div>`; }
function renderDataView(name) {
  const el = $(`#${name}-view`);
  if (name === 'notes') { el.innerHTML = viewHeader('Gedanken', 'Halte spontane Ideen fest, ohne deinen Schreibfluss zu unterbrechen.', 'Gedanke hinzufügen') + `<div class="cards">${project.notes.map(n => `<article class="data-card"><span class="pill">${escape(n.status)}</span><p>💡 ${escape(n.text)}</p><small>${formatDate(n.createdAt)}</small></article>`).join('') || '<p>Noch keine Gedanken gespeichert.</p>'}</div>`; $('#view-add').onclick = addThought; }
  if (name === 'characters') { el.innerHTML = viewHeader('Figuren', 'Menschen, Motive und Beziehungen deiner Geschichte.', 'Figur erstellen') + `<div class="cards">${project.characters.map(c => `<article class="data-card"><small>${escape(c.role || 'FIGUR')}</small><h3>${escape(c.name)}</h3><p>${escape(c.age ? `${c.age} Jahre · ` : '')}${escape(c.description)}</p><span class="pill">${escape(c.traits || 'Noch offen')}</span></article>`).join('') || '<p>Noch keine Figuren angelegt.</p>'}</div>`; $('#view-add').onclick = addCharacter; }
  if (name === 'story') { el.innerHTML = viewHeader('Story & roter Faden', 'Behalte offene Fragen und Handlungsstränge im Blick.', 'Plot Thread') + project.plotThreads.map(t => `<article class="wide-card"><span class="pill">${escape(t.status)}</span><h3>${escape(t.name)}</h3><p>${escape(t.description)}</p><footer><small>Begonnen: ${escape(t.introducedChapter || '–')}</small><small>Zuletzt: ${escape(t.lastMentionedChapter || '–')}</small></footer></article>`).join(''); $('#view-add').onclick = addThread; }
  if (name === 'timeline') el.innerHTML = viewHeader('Timeline', 'Chronologische Fakten werden in der nächsten Ausbaustufe hier gepflegt.') + '<div class="wide-card">Noch keine Timeline-Einträge.</div>';
  if (name === 'memory') { el.innerHTML = viewHeader('AI Memory', 'Transparente Story-Fakten, die der Assistent berücksichtigen darf.', 'Story-Wissen aktualisieren') + `<div class="wide-card"><h3>Buchzusammenfassung</h3><p>${escape(project.memory.bookSummary || 'Noch keine Zusammenfassung erstellt.')}</p></div>`; $('#view-add').onclick = () => runAI('memory', 'Analysiere die Projektdaten und erstelle eine knappe, strukturierte Zusammenfassung etablierter Story-Fakten. Keine Spekulationen.', true); }
}
function openForm(title, fields, onSubmit) { $('#form-title').textContent = title; $('#form-fields').innerHTML = fields; $('#form-dialog').showModal(); $('#generic-form').onsubmit = event => { event.preventDefault(); onSubmit(Object.fromEntries(new FormData(event.target))); $('#form-dialog').close(); }; }
function addThought(prefill = '') { openForm('Gedanke festhalten', `<label>Dein Gedanke<textarea name="text" required>${escape(prefill)}</textarea></label><label>Status<select name="status"><option>unsortiert</option><option>übernommen</option><option>verworfen</option></select></label>`, data => { project.notes.push({ id: uid(), ...data, createdAt: new Date().toISOString(), tags: [], relatedCharacters: [], relatedChapters: [] }); queueSave(); renderDataView('notes'); }); }
function addCharacter() { openForm('Figur erstellen', '<div class="two"><label>Name<input name="name" required></label><label>Alter<input name="age"></label></div><label>Beschreibung<textarea name="description"></textarea></label><label>Charaktereigenschaften<input name="traits"></label><label>Hintergrund<textarea name="background"></textarea></label><div class="two"><label>Ziele<input name="goals"></label><label>Ängste<input name="fears"></label></div><label>Beziehungen / Geheimnisse / Notizen<textarea name="notes"></textarea></label>', data => { project.characters.push({ id: uid(), ...data }); queueSave(); renderDataView('characters'); }); }
function addThread() { openForm('Plot Thread erstellen', '<label>Name<input name="name" required></label><label>Beschreibung<textarea name="description"></textarea></label><div class="two"><label>Status<select name="status"><option>offen</option><option>aktiv</option><option>gelöst</option></select></label><label>Eingeführt in<input name="introducedChapter"></label></div><label>Zuletzt erwähnt<input name="lastMentionedChapter"></label><label>Notizen<textarea name="notes"></textarea></label>', data => { project.plotThreads.push({ id: uid(), ...data, resolvedChapter: '' }); queueSave(); renderDataView('story'); }); }
function trashProject(id) { const p = projects.find(x => x.id === id); if (!confirm('Du bist dabei, das gesamte Buchprojekt inklusive aller Kapitel, Figuren, Gedanken und Story-Daten in den Papierkorb zu verschieben. Fortfahren?')) return; const typed = prompt(`Zum Verschieben bitte Projektnamen exakt eingeben:\n${p.title}`); if (typed !== p.title) return toast('Projektname stimmt nicht überein.'); exportProject(p); p.trashedAt = new Date().toISOString(); saveProject(p).then(() => renderDashboard()); }
async function purgeProject(id) { const p = projects.find(x => x.id === id); const typed = prompt(`Das löscht das Projekt endgültig. Bitte exakt eingeben:\n${p.title}`); if (typed !== p.title) return toast('Projektname stimmt nicht überein.'); exportProject(p); await removeProject(id); projects = projects.filter(x => x.id !== id); renderDashboard(true); }
function chapterMenu(id) { const item = project.chapters.find(x => x.id === id); const action = prompt('Aktion eingeben: umbenennen, hoch, runter oder löschen'); const index = project.chapters.indexOf(item); if (action === 'umbenennen') item.title = prompt('Neuer Kapitelname', item.title) || item.title; if (action === 'hoch' && index > 0) [project.chapters[index - 1], project.chapters[index]] = [item, project.chapters[index - 1]]; if (action === 'runter' && index < project.chapters.length - 1) [project.chapters[index + 1], project.chapters[index]] = [item, project.chapters[index + 1]]; if (action === 'löschen' && project.chapters.length > 1 && confirm(`„${item.title}“ wirklich löschen?`)) { project.chapters.splice(index, 1); chapter = project.chapters[Math.max(0, index - 1)]; } queueSave(); selectChapter(chapter.id); }
async function runAI(action, message, preview = false) { if (!project || !chapter) return; const selected = $('#editor').value.slice($('#editor').selectionStart, $('#editor').selectionEnd); addChat(message, 'user'); try { addChat('Ich denke nach …', 'ai', true); const answer = await askAI(project, chapter, action, message, selected); $('#chat .pending')?.remove(); if (preview || ['continue', 'improve', 'memory'].includes(action)) showPreview(action, answer, selected); else addChat(answer, 'ai'); } catch (error) { $('#chat .pending')?.remove(); addChat(error.message, 'ai'); } }
function addChat(text, type, pending = false) { $('#chat').insertAdjacentHTML('beforeend', `<div class="${type === 'ai' ? 'ai-message' : 'user-message'} ${pending ? 'pending' : ''}">${type === 'ai' ? '<b>✦ Schreibassistent</b>' : ''}<p>${escape(text)}</p></div>`); $('#chat').scrollTop = $('#chat').scrollHeight; }
function showPreview(action, answer, selected) { aiPending = { action, answer, selected, start: $('#editor').selectionStart, end: $('#editor').selectionEnd }; $('#original-wrap').classList.toggle('hidden', action !== 'improve'); $('#original-text').textContent = selected; $('#suggestion-text').textContent = answer; $('#preview-dialog').showModal(); }

$('#editor').oninput = () => { chapter.content = $('#editor').value; updateCount(); queueSave(); }; $('#chapter-title').oninput = () => { chapter.title = $('#chapter-title').value; renderChapters(); queueSave(); };
$('#new-project').onclick = () => $('#project-dialog').showModal(); $$('.create-project').forEach(b => b.onclick = () => $('#project-dialog').showModal()); $$('.close').forEach(b => b.onclick = () => $('#project-dialog').close());
$('#project-form').onsubmit = async event => { event.preventDefault(); const p = makeProject(Object.fromEntries(new FormData(event.target))); projects.push(p); await saveProject(p); $('#project-dialog').close(); event.target.reset(); openProject(p.id); };
$('#back-btn').onclick = async () => { if (project) await saveProject(project); renderDashboard(); }; $('#trash-toggle').onclick = event => { const active = event.currentTarget.dataset.active === 'yes'; event.currentTarget.dataset.active = active ? 'no' : 'yes'; event.currentTarget.firstChild.textContent = active ? 'Papierkorb ' : 'Projekte '; renderDashboard(!active); };
$('#add-chapter').onclick = () => { const title = prompt('Name des neuen Kapitels', `Kapitel ${project.chapters.length + 1}`); if (!title) return; chapter = { id: uid(), title, content: '' }; project.chapters.push(chapter); selectChapter(chapter.id); queueSave(); };
$('#save-thought').onclick = () => addThought($('#editor').value.slice($('#editor').selectionStart, $('#editor').selectionEnd)); $('#continue-btn').onclick = () => runAI('continue', 'Schreibe eine mögliche Fortsetzung. Behalte Stil und Perspektive bei.'); $('#improve-btn').onclick = () => runAI('improve', 'Verbessere den markierten Text stilistisch, ohne seine Aussage zu verändern.');
$$('#sections button').forEach(b => b.onclick = () => showView(b.dataset.view)); $$('.quick button').forEach(b => b.onclick = () => runAI(b.dataset.action, ({ continue: 'Schreibe eine mögliche Fortsetzung.', brainstorm: 'Gib mir fünf passende Ideen für die weitere Handlung.', improve: 'Verbessere den markierten Text.', thread: 'Prüfe offene Handlungsfäden und schlage nächste Schritte vor.' })[b.dataset.action]));
$('#chat-form').onsubmit = event => { event.preventDefault(); const value = $('#chat-input').value.trim(); if (value) { runAI('chat', value); $('#chat-input').value = ''; } };
$$('.close-generic').forEach(b => b.onclick = () => $('#form-dialog').close()); $$('.close-preview').forEach(b => b.onclick = () => $('#preview-dialog').close());
$('#accept-ai').onclick = () => { const { action, answer, start, end } = aiPending; if (action === 'memory') project.memory.bookSummary = answer; else if (action === 'improve') chapter.content = chapter.content.slice(0, start) + answer + chapter.content.slice(end); else chapter.content += `${chapter.content ? '\n\n' : ''}${answer}`; $('#editor').value = chapter.content; updateCount(); queueSave(); $('#preview-dialog').close(); if (action === 'memory') renderDataView('memory'); };
$('#connect-folder').onclick = async () => { try { await connectFolder(project); updateStorageState(); toast('Projektordner verbunden und Dateien geschrieben.'); } catch (error) { toast(error.message); } }; function updateStorageState() { $('#local-warning').textContent = project.directoryHandle ? 'Lokal verbunden ✓' : 'Nur in diesem Browser gespeichert'; }
$('#export-btn').onclick = () => { const choice = prompt('Exportformat eingeben: json oder markdown', 'json'); choice === 'markdown' ? exportManuscript(project) : exportProject(project); }; $('#logout-btn').onclick = async () => { await fetch('/api/logout', { method: 'POST' }); location.replace('index.html'); };
start().catch(error => { console.error(error); toast('Die lokalen Projekte konnten nicht geladen werden.'); });
